// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_zLHaI5yVQpzvglQpBu0QxYDLyBRfyUo',
    appId: '1:762839508808:web:f7d194eb9f660129a4757d',
    messagingSenderId: '762839508808',
    projectId: 'expense-tracker-bdc88',
    authDomain: 'expense-tracker-bdc88.firebaseapp.com',
    storageBucket: 'expense-tracker-bdc88.firebasestorage.app',
    measurementId: 'G-N8SBME8S3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChJibi5900CE1O8Y_pXAswki5Efpzwups',
    appId: '1:762839508808:android:b04ad947a08c9745a4757d',
    messagingSenderId: '762839508808',
    projectId: 'expense-tracker-bdc88',
    storageBucket: 'expense-tracker-bdc88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD32fSRWCryXx6Ktg8roSzbhPQJkp-ma78',
    appId: '1:762839508808:ios:716c56c9f920eb46a4757d',
    messagingSenderId: '762839508808',
    projectId: 'expense-tracker-bdc88',
    storageBucket: 'expense-tracker-bdc88.firebasestorage.app',
    iosBundleId: 'com.expensetracker.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_zLHaI5yVQpzvglQpBu0QxYDLyBRfyUo',
    appId: '1:762839508808:web:c980e26b37dd1627a4757d',
    messagingSenderId: '762839508808',
    projectId: 'expense-tracker-bdc88',
    authDomain: 'expense-tracker-bdc88.firebaseapp.com',
    storageBucket: 'expense-tracker-bdc88.firebasestorage.app',
    measurementId: 'G-C08FVX8VD2',
  );
}
