// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:expense_tracker/models/date_entry_model.dart';
import 'package:expense_tracker/models/transaction_category.dart';
import 'package:expense_tracker/models/transaction_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DateEntryModelAdapter());
    registerAdapter(TransactionCategoryAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DateEntryModelAdapter());
    registerAdapter(TransactionCategoryAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}
